builds:
- env:
  - CGO_ENABLED=0
- goos:
  - windows
  - darwin
  - linux
archive:
  replacements:
    darwin: MacOS
    linux: Linux
    windows: Windows
    386: 32-bit
    amd64: 64-bit
  wrap_in_directory: true
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'